# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models

from tn_parser.transport.models import DataProviderTypes

ROUTES_URL_OF_HTML = 'http://transport.nov.ru/urban_trans/1'


def forwards_func(apps, schema_editor):
    DataProviderUrl = apps.get_model("transport", "DataProviderUrl")

    if ROUTES_URL_OF_HTML:
        db_alias = schema_editor.connection.alias
        DataProviderUrl.objects.using(db_alias).update_or_create(
            link=ROUTES_URL_OF_HTML,
            type=DataProviderTypes.ROUTES_HTML_PAGE,
            coding='cp1251',
        )


def reverse_func(apps, schema_editor):
    DataProviderUrl = apps.get_model("transport", "DataProviderUrl")

    db_alias = schema_editor.connection.alias
    DataProviderUrl.objects.using(db_alias) \
        .filter(
        type=DataProviderTypes.ROUTES_HTML_PAGE,) \
        .delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

